//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmak.Integrations.Volvo.Oasis.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OasisSampleResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OasisSampleResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karmak.Integrations.Volvo.Oasis.Tests.OasisSampleResponses", typeof(OasisSampleResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&apos;http://volvo.com/goasis&apos;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;EN&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;EN&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT&gt;
        ///   &lt;VEHICLE-INQUIRY&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompleteVehicleResponse {
            get {
                return ResourceManager.GetString("CompleteVehicleResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithCampNumberInBcmTextLine {
            get {
                return ResourceManager.GetString("ResponseWithCampNumberInBcmTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithGsbNumberInBcmTextLine {
            get {
                return ResourceManager.GetString("ResponseWithGsbNumberInBcmTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///    &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///    &lt;DLR-LANG-RESP&gt;
        ///        &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///        &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///        &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///        &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///        &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///        &lt;LANG-RESP-MSG&gt;&lt;/LANG-RESP-MSG&gt;
        ///    &lt;/DLR-LANG-RESP&gt;
        ///    &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithMultipleVehEspDetailBlocks {
            get {
                return ResourceManager.GetString("ResponseWithMultipleVehEspDetailBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithSsmNumberInBcmTextLine {
            get {
                return ResourceManager.GetString("ResponseWithSsmNumberInBcmTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithTsbNumberInBcmTextLine {
            get {
                return ResourceManager.GetString("ResponseWithTsbNumberInBcmTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&apos;http://volvo.com/goasis&apos;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithUnknownXml {
            get {
                return ResourceManager.GetString("ResponseWithUnknownXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///    &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///    &lt;DLR-LANG-RESP&gt;
        ///        &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///        &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///        &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///        &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///        &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///        &lt;LANG-RESP-MSG&gt;&lt;/LANG-RESP-MSG&gt;
        ///    &lt;/DLR-LANG-RESP&gt;
        ///    &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithVehicleSystemMessages {
            get {
                return ResourceManager.GetString("ResponseWithVehicleSystemMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidResponseWithOnlyBroadcastMessages {
            get {
                return ResourceManager.GetString("ValidResponseWithOnlyBroadcastMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT&gt;
        ///   &lt;VEHICLE-INQUIRY&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidVehicleResponse {
            get {
                return ResourceManager.GetString("ValidVehicleResponse", resourceCulture);
            }
        }
    }
}
