//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmak.Integrations.Volvo.Oasis.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleOwsSoapResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleOwsSoapResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karmak.Integrations.Volvo.Oasis.Tests.SampleOwsSoapResponses", typeof(SampleOwsSoapResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Header&gt;&lt;/soap:Header&gt;&lt;soapenv:Body wsu:Id=&quot;Id-68843004-350e-4c48-a630-e26c9f5875c6&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;ProcessMessageResponse xmlns=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;&lt;payload&gt;&lt;tran:content xmlns:ns=&quot;http://www.starstandard.org/STAR/5&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConditionCodes {
            get {
                return ResourceManager.GetString("ConditionCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Header&gt;&lt;/soap:Header&gt;&lt;soapenv:Body wsu:Id=&quot;Id-913d648f-98b9-40d0-8932-e26c9f58c3bb&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;ProcessMessageResponse xmlns=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;&lt;payload&gt;&lt;tran:content xmlns:star=&quot;http://www.starstandard.org/STAR/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerConcernCodes {
            get {
                return ResourceManager.GetString("CustomerConcernCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Header&gt;&lt;/soap:Header&gt;&lt;soapenv:Body wsu:Id=&quot;Id-7d2b1a9a-c122-4e56-a731-e26c9f583229&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;ProcessMessageResponse xmlns=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;&lt;payload&gt;&lt;ns:ShowStandardCodes xmlns:ns=&quot;http://www.starstandard.org [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DamageCodes {
            get {
                return ResourceManager.GetString("DamageCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///&lt;soap:Header&gt;&lt;/soap:Header&gt;
        ///&lt;SOAP:Body wsu:Id=&quot;Id-f346f441-6409-4da9-a732-e26c9f5816f1&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:syncp=&quot;urn:volvo/syncp/v1.0&quot; xmlns:STAR=&quot;http://www.starstandard.org/STAR/5&quot; xmlns:SOAP=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;SOAP:Fault&gt;&lt;faultcode&gt;SOAP:Client&lt;/faultcode&gt;&lt;faultstring&gt;Invalid or missing @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FailureSoapFault {
            get {
                return ResourceManager.GetString("FailureSoapFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&apos;http://volvo.com/goasis&apos;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT&gt;
        ///   &lt;VEHICLE-INQUIRY&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OasisValidVehicleResponseXml {
            get {
                return ResourceManager.GetString("OasisValidVehicleResponseXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///    &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///    &lt;DLR-LANG-RESP&gt;
        ///        &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///        &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///        &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///        &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///        &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///        &lt;LANG-RESP-MSG&gt;&lt;/LANG-RESP-MSG&gt;
        ///    &lt;/DLR-LANG-RESP&gt;
        ///    &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithExtendedServicePlanMultiplePlansSingleLabel {
            get {
                return ResourceManager.GetString("ResponseWithExtendedServicePlanMultiplePlansSingleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&apos;http://volvo.com/goasis&apos;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;VEH-LINE FAMILY=&apos;VL&apos; FEATURE=&apos;M2&apos;&gt;Escape&lt;/VEH-LINE&gt;
        ///   &lt;VEH-SERIES FAMILY=&apos;&apos; FEATURE=&apos;&apos;/&gt;
        ///&lt;/GOASIS&gt;.
        /// </summary>
        internal static string ResponseWithNullableVehicleFeature {
            get {
                return ResourceManager.GetString("ResponseWithNullableVehicleFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&apos;http://volvo.com/goasis&apos;&gt;
        ///   &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///   &lt;DLR-LANG-RESP&gt;
        ///      &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///      &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///      &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///      &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///      &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///      &lt;LANG-RESP-MSG /&gt;
        ///   &lt;/DLR-LANG-RESP&gt;
        ///   &lt;BROADCAST-MESSAGES&gt;
        ///      &lt;BCM-HEADER-LIT&gt;BROADCAST MESSAGES&lt;/BCM-HEADER-LIT&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithUnexpectedTagsInBCM {
            get {
                return ResourceManager.GetString("ResponseWithUnexpectedTagsInBCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;GOASIS xmlns=&quot;http://volvo.com/goasis&quot;&gt;
        ///    &lt;GOASIS-RESULT-LIT&gt;OASIS RESULT:&lt;/GOASIS-RESULT-LIT&gt;
        ///    &lt;DLR-LANG-RESP&gt;
        ///        &lt;RET-LANG-CODE&gt;EN&lt;/RET-LANG-CODE&gt;
        ///        &lt;RET-LANG-DESC&gt;ENGLISH&lt;/RET-LANG-DESC&gt;
        ///        &lt;PREF-LANG-CODE&gt;EN&lt;/PREF-LANG-CODE&gt;
        ///        &lt;OPT-LANG-CODE-1&gt;ES&lt;/OPT-LANG-CODE-1&gt;
        ///        &lt;OPT-LANG-CODE-2&gt;FR&lt;/OPT-LANG-CODE-2&gt;
        ///        &lt;LANG-RESP-MSG&gt;&lt;/LANG-RESP-MSG&gt;
        ///    &lt;/DLR-LANG-RESP&gt;
        ///    &lt;VEHICLE-INFO-LIT&gt;Vehicle Information&lt;/VEHICLE-INFO-LIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResponseWithVehicleSystemMessages {
            get {
                return ResourceManager.GetString("ResponseWithVehicleSystemMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;soap:Header&gt;&lt;/soap:Header&gt;&lt;soapenv:Body wsu:Id=&quot;Id-93e08d4a-3fb9-4f9d-b19c-e26c9f584a6c&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;		&lt;soapenv:Fault&gt;			&lt;faultcode&gt;soapenv:Client&lt;/faultcode&gt;			&lt;faultstring&gt;Not valid Soap Header&lt;/faultstring&gt;			&lt;detail&gt;				&lt;ErrorMessage&gt;NameSpace : urn:volvo/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoapFault {
            get {
                return ResourceManager.GetString("SoapFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///code,desc
        ///100000,          BODY
        ///101000,Seating
        ///102000,Window/Glass
        ///103000,Mirrors
        ///104000,Restraint Systems/Air Bags
        ///105000,Roof Options
        ///106000,Paint/Finish
        ///107000,Interior Trim
        ///108000,Exterior/Accessories
        ///110000,Sealing
        ///111000,Body Panel(s)/Unibody
        ///112000,Latches/Locks &amp; Security
        ///190000,Publications Revisions/Updates
        ///200000,          ELECTRICAL
        ///201000,Lighting Systems
        ///201100, * Interior Lighting
        ///201200, * Exterior Lighting
        ///202000,Wiper/Washer System
        ///203000,Basic Electrical
        ///203100, * Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SymptomCodesCsv {
            get {
                return ResourceManager.GetString("SymptomCodesCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///code,desc
        ///100000,          BODY
        ///101000,Seating,Foobar
        ///    .
        /// </summary>
        internal static string SymptomCodesCsvWith3ColumnsRow {
            get {
                return ResourceManager.GetString("SymptomCodesCsvWith3ColumnsRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///   &lt;soap:Header /&gt;
        ///   &lt;soapenv:Body xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; wsu:Id=&quot;Id-68843004-350e-4c48-a630-e26c9f5875c6&quot;&gt;
        ///      &lt;ProcessMessageResponse xmlns=&quot;http://www.starstandards.org/webservices/2005/10/transport&quot;&gt;
        ///         &lt;payload&gt;
        ///            &lt;tran:content xmlns:tran=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnexpectedSoapResponse {
            get {
                return ResourceManager.GetString("UnexpectedSoapResponse", resourceCulture);
            }
        }
    }
}
