using System.Collections.Generic;
using System.Linq;

namespace Karmak.Integrations.Volvo.React.Utils
{
    public class CountryInfoList
    {
        public static readonly IEnumerable<CountryInfo> All = new List<CountryInfo> {
            new CountryInfo("Aland Islands", "AX", "ALA"),
            new CountryInfo("Albania", "AL", "ALB"),
            new CountryInfo("Algeria", "DZ", "DZA"),
            new CountryInfo("American Samoa", "AS", "ASM"),
            new CountryInfo("Andorra", "AD", "AND"),
            new CountryInfo("Angola", "AO", "AGO"),
            new CountryInfo("Anguilla", "AI", "AIA"),
            new CountryInfo("Antarctica", "AQ", "ATA"),
            new CountryInfo("Antigua and Barbuda", "AG", "ATG"),
            new CountryInfo("Argentina", "AR", "ARG"),
            new CountryInfo("Armenia", "AM", "ARM"),
            new CountryInfo("Aruba", "AW", "ABW"),
            new CountryInfo("Australia", "AU", "AUS"),
            new CountryInfo("Austria", "AT", "AUT"),
            new CountryInfo("Azerbaijan", "AZ", "AZE"),
            new CountryInfo("Bahamas", "BS", "BHS"),
            new CountryInfo("Bahrain", "BH", "BHR"),
            new CountryInfo("Bangladesh", "BD", "BGD"),
            new CountryInfo("Barbados", "BB", "BRB"),
            new CountryInfo("Belarus", "BY", "BLR"),
            new CountryInfo("Belgium", "BE", "BEL"),
            new CountryInfo("Belize", "BZ", "BLZ"),
            new CountryInfo("Benin", "BJ", "BEN"),
            new CountryInfo("Bermuda", "BM", "BMU"),
            new CountryInfo("Bhutan", "BT", "BTN"),
            new CountryInfo("Bolivia (Plurinational State of)", "BO", "BOL"),
            new CountryInfo("Bonaire, Sint Eustatius and Saba", "BQ", "BES"),
            new CountryInfo("Bosnia and Herzegovina", "BA", "BIH"),
            new CountryInfo("Botswana", "BW", "BWA"),
            new CountryInfo("Bouvet Island", "BV", "BVT"),
            new CountryInfo("Brazil", "BR", "BRA"),
            new CountryInfo("British Indian Ocean Territory", "IO", "IOT"),
            new CountryInfo("Brunei Darussalam", "BN", "BRN"),
            new CountryInfo("Bulgaria", "BG", "BGR"),
            new CountryInfo("Burkina Faso", "BF", "BFA"),
            new CountryInfo("Burundi", "BI", "BDI"),
            new CountryInfo("Cabo Verde", "CV", "CPV"),
            new CountryInfo("Cambodia", "KH", "KHM"),
            new CountryInfo("Cameroon", "CM", "CMR"),
            new CountryInfo("Canada", "CA", "CAN"),
            new CountryInfo("Cayman Islands", "KY", "CYM"),
            new CountryInfo("Central African Republic", "CF", "CAF"),
            new CountryInfo("Chad", "TD", "TCD"),
            new CountryInfo("Chile", "CL", "CHL"),
            new CountryInfo("China", "CN", "CHN"),
            new CountryInfo("Christmas Island", "CX", "CXR"),
            new CountryInfo("Cocos (Keeling) Islands", "CC", "CCK"),
            new CountryInfo("Colombia", "CO", "COL"),
            new CountryInfo("Comoros", "KM", "COM"),
            new CountryInfo("Congo", "CG", "COG"),
            new CountryInfo("Congo, Democratic Republic of the", "CD", "COD"),
            new CountryInfo("Cook Islands", "CK", "COK"),
            new CountryInfo("Costa Rica", "CR", "CRI"),
            new CountryInfo("Cote d'Ivoire", "CI", "CIV"),
            new CountryInfo("Croatia", "HR", "HRV"),
            new CountryInfo("Cuba", "CU", "CUB"),
            new CountryInfo("Curaçao", "CW", "CUW"),
            new CountryInfo("Cyprus", "CY", "CYP"),
            new CountryInfo("Czechia", "CZ", "CZE"),
            new CountryInfo("Denmark", "DK", "DNK"),
            new CountryInfo("Djibouti", "DJ", "DJI"),
            new CountryInfo("Dominica", "DM", "DMA"),
            new CountryInfo("Dominican Republic", "DO", "DOM"),
            new CountryInfo("Ecuador", "EC", "ECU"),
            new CountryInfo("Egypt", "EG", "EGY"),
            new CountryInfo("El Salvador", "SV", "SLV"),
            new CountryInfo("Equatorial Guinea", "GQ", "GNQ"),
            new CountryInfo("Eritrea", "ER", "ERI"),
            new CountryInfo("Estonia", "EE", "EST"),
            new CountryInfo("Eswatini", "SZ", "SWZ"),
            new CountryInfo("Ethiopia", "ET", "ETH"),
            new CountryInfo("Falkland Islands (Malvinas)", "FK", "FLK"),
            new CountryInfo("Faroe Islands", "FO", "FRO"),
            new CountryInfo("Fiji", "FJ", "FJI"),
            new CountryInfo("Finland", "FI", "FIN"),
            new CountryInfo("France", "FR", "FRA"),
            new CountryInfo("French Guiana", "GF", "GUF"),
            new CountryInfo("French Polynesia", "PF", "PYF"),
            new CountryInfo("French Southern Territories", "TF", "ATF"),
            new CountryInfo("Gabon", "GA", "GAB"),
            new CountryInfo("Gambia", "GM", "GMB"),
            new CountryInfo("Georgia", "GE", "GEO"),
            new CountryInfo("Germany", "DE", "DEU"),
            new CountryInfo("Ghana", "GH", "GHA"),
            new CountryInfo("Gibraltar", "GI", "GIB"),
            new CountryInfo("Greece", "GR", "GRC"),
            new CountryInfo("Greenland", "GL", "GRL"),
            new CountryInfo("Grenada", "GD", "GRD"),
            new CountryInfo("Guadeloupe", "GP", "GLP"),
            new CountryInfo("Guam", "GU", "GUM"),
            new CountryInfo("Guatemala", "GT", "GTM"),
            new CountryInfo("Guernsey", "GG", "GGY"),
            new CountryInfo("Guinea", "GN", "GIN"),
            new CountryInfo("Guinea-Bissau", "GW", "GNB"),
            new CountryInfo("Guyana", "GY", "GUY"),
            new CountryInfo("Haiti", "HT", "HTI"),
            new CountryInfo("Heard Island and McDonald Islands", "HM", "HMD"),
            new CountryInfo("Holy See", "VA", "VAT"),
            new CountryInfo("Honduras", "HN", "HND"),
            new CountryInfo("Hong Kong", "HK", "HKG"),
            new CountryInfo("Hungary", "HU", "HUN"),
            new CountryInfo("Iceland", "IS", "ISL"),
            new CountryInfo("India", "IN", "IND"),
            new CountryInfo("Indonesia", "ID", "IDN"),
            new CountryInfo("Iran (Islamic Republic of)", "IR", "IRN"),
            new CountryInfo("Iraq", "IQ", "IRQ"),
            new CountryInfo("Ireland", "IE", "IRL"),
            new CountryInfo("Isle of Man", "IM", "IMN"),
            new CountryInfo("Israel", "IL", "ISR"),
            new CountryInfo("Italy", "IT", "ITA"),
            new CountryInfo("Jamaica", "JM", "JAM"),
            new CountryInfo("Japan", "JP", "JPN"),
            new CountryInfo("Jersey", "JE", "JEY"),
            new CountryInfo("Jordan", "JO", "JOR"),
            new CountryInfo("Kazakhstan", "KZ", "KAZ"),
            new CountryInfo("Kenya", "KE", "KEN"),
            new CountryInfo("Kiribati", "KI", "KIR"),
            new CountryInfo("Korea (Democratic People's Republic of)", "KP", "PRK"),
            new CountryInfo("Korea, Republic of", "KR", "KOR"),
            new CountryInfo("Kuwait", "KW", "KWT"),
            new CountryInfo("Kyrgyzstan", "KG", "KGZ"),
            new CountryInfo("Lao People's Democratic Republic", "LA", "LAO"),
            new CountryInfo("Latvia", "LV", "LVA"),
            new CountryInfo("Lebanon", "LB", "LBN"),
            new CountryInfo("Lesotho", "LS", "LSO"),
            new CountryInfo("Liberia", "LR", "LBR"),
            new CountryInfo("Libya", "LY", "LBY"),
            new CountryInfo("Liechtenstein", "LI", "LIE"),
            new CountryInfo("Lithuania", "LT", "LTU"),
            new CountryInfo("Luxembourg", "LU", "LUX"),
            new CountryInfo("Macao", "MO", "MAC"),
            new CountryInfo("Madagascar", "MG", "MDG"),
            new CountryInfo("Malawi", "MW", "MWI"),
            new CountryInfo("Malaysia", "MY", "MYS"),
            new CountryInfo("Maldives", "MV", "MDV"),
            new CountryInfo("Mali", "ML", "MLI"),
            new CountryInfo("Malta", "MT", "MLT"),
            new CountryInfo("Marshall Islands", "MH", "MHL"),
            new CountryInfo("Martinique", "MQ", "MTQ"),
            new CountryInfo("Mauritania", "MR", "MRT"),
            new CountryInfo("Mauritius", "MU", "MUS"),
            new CountryInfo("Mayotte", "YT", "MYT"),
            new CountryInfo("Mexico", "MX", "MEX"),
            new CountryInfo("Micronesia (Federated States of)", "FM", "FSM"),
            new CountryInfo("Moldova, Republic of", "MD", "MDA"),
            new CountryInfo("Monaco", "MC", "MCO"),
            new CountryInfo("Mongolia", "MN", "MNG"),
            new CountryInfo("Montenegro", "ME", "MNE"),
            new CountryInfo("Montserrat", "MS", "MSR"),
            new CountryInfo("Morocco", "MA", "MAR"),
            new CountryInfo("Mozambique", "MZ", "MOZ"),
            new CountryInfo("Myanmar", "MM", "MMR"),
            new CountryInfo("Namibia", "NA", "NAM"),
            new CountryInfo("Nauru", "NR", "NRU"),
            new CountryInfo("Nepal", "NP", "NPL"),
            new CountryInfo("Netherlands", "NL", "NLD"),
            new CountryInfo("New Caledonia", "NC", "NCL"),
            new CountryInfo("New Zealand", "NZ", "NZL"),
            new CountryInfo("Nicaragua", "NI", "NIC"),
            new CountryInfo("Niger", "NE", "NER"),
            new CountryInfo("Nigeria", "NG", "NGA"),
            new CountryInfo("Niue", "NU", "NIU"),
            new CountryInfo("Norfolk Island", "NF", "NFK"),
            new CountryInfo("North Macedonia", "MK", "MKD"),
            new CountryInfo("Northern Mariana Islands", "MP", "MNP"),
            new CountryInfo("Norway", "NO", "NOR"),
            new CountryInfo("Oman", "OM", "OMN"),
            new CountryInfo("Pakistan", "PK", "PAK"),
            new CountryInfo("Palau", "PW", "PLW"),
            new CountryInfo("Palestine, State of", "PS", "PSE"),
            new CountryInfo("Panama", "PA", "PAN"),
            new CountryInfo("Papua New Guinea", "PG", "PNG"),
            new CountryInfo("Paraguay", "PY", "PRY"),
            new CountryInfo("Peru", "PE", "PER"),
            new CountryInfo("Philippines", "PH", "PHL"),
            new CountryInfo("Pitcairn", "PN", "PCN"),
            new CountryInfo("Poland", "PL", "POL"),
            new CountryInfo("Portugal", "PT", "PRT"),
            new CountryInfo("Puerto Rico", "PR", "PRI"),
            new CountryInfo("Qatar", "QA", "QAT"),
            new CountryInfo("Reunion", "RE", "REU"),
            new CountryInfo("Romania", "RO", "ROU"),
            new CountryInfo("Russian Federation", "RU", "RUS"),
            new CountryInfo("Rwanda", "RW", "RWA"),
            new CountryInfo("Saint Barthelemy", "BL", "BLM"),
            new CountryInfo("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN"),
            new CountryInfo("Saint Kitts and Nevis", "KN", "KNA"),
            new CountryInfo("Saint Lucia", "LC", "LCA"),
            new CountryInfo("Saint Martin (French part)", "MF", "MAF"),
            new CountryInfo("Saint Pierre and Miquelon", "PM", "SPM"),
            new CountryInfo("Saint Vincent and the Grenadines", "VC", "VCT"),
            new CountryInfo("Samoa", "WS", "WSM"),
            new CountryInfo("San Marino", "SM", "SMR"),
            new CountryInfo("Sao Tome and Principe", "ST", "STP"),
            new CountryInfo("Saudi Arabia", "SA", "SAU"),
            new CountryInfo("Senegal", "SN", "SEN"),
            new CountryInfo("Serbia", "RS", "SRB"),
            new CountryInfo("Seychelles", "SC", "SYC"),
            new CountryInfo("Sierra Leone", "SL", "SLE"),
            new CountryInfo("Singapore", "SG", "SGP"),
            new CountryInfo("Sint Maarten (Dutch part)", "SX", "SXM"),
            new CountryInfo("Slovakia", "SK", "SVK"),
            new CountryInfo("Slovenia", "SI", "SVN"),
            new CountryInfo("Solomon Islands", "SB", "SLB"),
            new CountryInfo("Somalia", "SO", "SOM"),
            new CountryInfo("South Africa", "ZA", "ZAF"),
            new CountryInfo("South Georgia and the South Sandwich Islands", "GS", "SGS"),
            new CountryInfo("South Sudan", "SS", "SSD"),
            new CountryInfo("Spain", "ES", "ESP"),
            new CountryInfo("Sri Lanka", "LK", "LKA"),
            new CountryInfo("Sudan", "SD", "SDN"),
            new CountryInfo("Suriname", "SR", "SUR"),
            new CountryInfo("Svalbard and Jan Mayen", "SJ", "SJM"),
            new CountryInfo("Sweden", "SE", "SWE"),
            new CountryInfo("Switzerland", "CH", "CHE"),
            new CountryInfo("Syrian Arab Republic", "SY", "SYR"),
            new CountryInfo("Taiwan, Province of China", "TW", "TWN"),
            new CountryInfo("Tajikistan", "TJ", "TJK"),
            new CountryInfo("Tanzania, United Republic of", "TZ", "TZA"),
            new CountryInfo("Thailand", "TH", "THA"),
            new CountryInfo("Timor-Leste", "TL", "TLS"),
            new CountryInfo("Togo", "TG", "TGO"),
            new CountryInfo("Tokelau", "TK", "TKL"),
            new CountryInfo("Tonga", "TO", "TON"),
            new CountryInfo("Trinidad and Tobago", "TT", "TTO"),
            new CountryInfo("Tunisia", "TN", "TUN"),
            new CountryInfo("Turkey", "TR", "TUR"),
            new CountryInfo("Turkmenistan", "TM", "TKM"),
            new CountryInfo("Turks and Caicos Islands", "TC", "TCA"),
            new CountryInfo("Tuvalu", "TV", "TUV"),
            new CountryInfo("Uganda", "UG", "UGA"),
            new CountryInfo("Ukraine", "UA", "UKR"),
            new CountryInfo("United Arab Emirates", "AE", "ARE"),
            new CountryInfo("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR"),
            new CountryInfo("United States of America", "US", "USA"),
            new CountryInfo("United States Minor Outlying Islands", "UM", "UMI"),
            new CountryInfo("Uruguay", "UY", "URY"),
            new CountryInfo("Uzbekistan", "UZ", "UZB"),
            new CountryInfo("Vanuatu", "VU", "VUT"),
            new CountryInfo("Venezuela (Bolivarian Republic of)", "VE", "VEN"),
            new CountryInfo("Viet Nam", "VN", "VNM"),
            new CountryInfo("Virgin Islands (British)", "VG", "VGB"),
            new CountryInfo("Virgin Islands (U.S.)", "VI", "VIR"),
            new CountryInfo("Wallis and Futuna", "WF", "WLF"),
            new CountryInfo("Western Sahara", "EH", "ESH"),
            new CountryInfo("Yemen", "YE", "YEM"),
            new CountryInfo("Zambia", "ZM", "ZMB"),
            new CountryInfo("Zimbabwe", "ZW", "ZWE")
        };

        public class CountryInfo
        {
            public string Name { get; }
            public string Alpha2 { get; }
            public string Alpha3 { get; }

            public CountryInfo(string name, string alpha2, string alpha3)
            {
                Name = name;
                Alpha2 = alpha2;
                Alpha3 = alpha3;
            }
        }

        public static Dictionary<string, CountryInfo> CountriesByAlpha2()
        {
            return All.ToDictionary(ci => ci.Alpha2.ToLower(), ci => ci);
        }

        public static Dictionary<string, CountryInfo> CountriesByAlpha3()
        {
            return All.ToDictionary(ci => ci.Alpha3.ToLower(), ci => ci);
        }

        public static Dictionary<string, CountryInfo> CountriesByName()
        {
            return All.ToDictionary(ci => ci.Name.ToLower(), ci => ci);
        }
    }
}