<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoBogus" Version="2.13.1" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MassTransit" Version="8.5.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Karmak.Integrations.Volvo.Common\Karmak.Integrations.Volvo.Common.csproj" />
    <ProjectReference Include="..\Karmak.Integrations.Volvo.Fusion\Karmak.Integrations.Volvo.Fusion.csproj" />
    <ProjectReference Include="..\Karmak.Integrations.Volvo.React\Karmak.Integrations.Volvo.React.csproj" />
    <ProjectReference Include="..\Karmak.Integrations.Volvo.React.Transport\Karmak.Integrations.Volvo.React.Transport.csproj" />
    <ProjectReference Include="..\Karmak.Integrations.Volvo.Warranty\Karmak.Integrations.Volvo.Warranty.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*" />
  </ItemGroup>

</Project>
